### ISSUE TITLE
Unable to reproduce the results - lack of training data  plus minor bugs

### ISSUE THREAD

**Issue by wgajek** [smousavi05/CRED#2]
parser.add_argument("--data_dir", dest='data_dir', default="../../STEAD/dataset6/waveforms_12_20_19.hdf5", type=str, help="Input file directory") #"../STEAD/dataset/waveforms.hdf5"  "./input/20101001WHAR.hdf5"
There is no data in your upload and no information on where to get it from. Consequently, I am unable to reproduce your work presented in the paper. 

Minor bugs:
Line 12: can't import Adam from keras, that is optimizer from tensorflow.keras not keras
you need to change to from tensorflow.keras.optimizers import Adam

Line 26: probem when importing from cred_utils (or importing cred_utils)
 AttributeError: module 'keras.utils' has no attribute 'Sequence'
you need to change keras.utils.Sequence to tf.keras.utils.Sequence in lines 28 and 314  (in cred_utils.py) and probably add 
import tensorflow as tf

**Comment by smousavi05** [comment]
@wgajek You need to get the data from https://github.com/smousavi05/STEAD
 those bugs are all related to the new version of Keras. In the new version they have moved many things to the tensorflow. You need to either fix those lines or get an older version of Keras i.e. < 1.8

**Comment by wgajek** [comment]
I think you need to specify version of keras (and python). Going below 1.8 is not ultimate solution (see below). **What version is required to run your code properly?**

I tried keras 1.2.2 python 3.6 butthe problem remains (AttributeError: module 'keras.utils' has no attribute 'Sequence')
I can switch it to tf.keras.utils - that works but results in additional errors which might be cause by keras version mismatch

when using tf.keras.utils instead keras.utils arguments hardcoded in input files do not match

----
**runfile('/home/wgajek/CRED/cred_original.py', wdir='/home/wgajek/CRED')**
Reloaded modules: lazylinker_ext, lazylinker_ext.lazylinker_ext, cred_utils
Mode is: test
Loading the model ...
Traceback (most recent call last):

  File "/home/wgajek/CRED/cred_original.py", line 209, in <module>
    model = load_model(args.input_model)

  File "/home/wgajek/anaconda3/envs/cred/lib/python3.6/site-packages/tensorflow/python/keras/engine/saving.py", line 244, in load_model
    optimizer_config, custom_objects=custom_objects)

  File "/home/wgajek/anaconda3/envs/cred/lib/python3.6/site-packages/tensorflow/python/keras/optimizers.py", line 790, in deserialize
    printable_module_name='optimizer')

  File "/home/wgajek/anaconda3/envs/cred/lib/python3.6/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 175, in deserialize_keras_object
    return cls.from_config(config['config'])

  File "/home/wgajek/anaconda3/envs/cred/lib/python3.6/site-packages/tensorflow/python/keras/optimizers.py", line 149, in from_config
    return cls(**config)

  File "/home/wgajek/anaconda3/envs/cred/lib/python3.6/site-packages/tensorflow/python/keras/optimizers.py", line 443, in __init__
    super(Adam, self).__init__(**kwargs)

  File "/home/wgajek/anaconda3/envs/cred/lib/python3.6/site-packages/tensorflow/python/keras/optimizers.py", line 58, in __init__
    'passed to optimizer: ' + str(k))

TypeError: Unexpected keyword argument passed to optimizer: learning_rate


**args.input_model**
Out[4]: './cred_original_outputs/models/cred_original_006.h5'
